module.exports = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SYNC_TIME: 'SYNC_TIME',
  NEW_VIDEO: 'NEW_VIDEO',
  ASK_FOR_VIDEO_URL: 'ASK_FOR_VIDEO_URL',
  SYNC_VIDEO_INFORMATION: 'SYNC_VIDEO_INFORMATION',
  ASK_FOR_VIDEO_INFORMATION: 'ASK_FOR_VIDEO_INFORMATION',
  JOIN_ROOM: 'JOIN_ROOM',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',
  ASK_FOR_USERNAME: 'ASK_FOR_USERNAME',
  SEND_USERNAME: 'SEND_USERNAME'
}