module.exports = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SYNC_TIME: 'SYNC_TIME',
  NEW_VIDEO: 'NEW_VIDEO',
  ASK_FOR_VIDEO_URL: 'ASK_FOR_VIDEO_URL',
  SYNC_VIDEO_INFORMATION: 'SYNC_VIDEO_INFORMATION',
  ASK_FOR_VIDEO_INFORMATION: 'ASK_FOR_VIDEO_INFORMATION'
}